import random

# Generate random movie data
def generate_movies(num_movies):
    titles = [
        "A Journey Through Shadows",
        "The Last Beacon",
        "Whispering Meadows",
        "Starlight Symphony",
        "Echoes of Eternity",
        "The Forgotten Voyage",
        "Beneath the Crimson Sky",
        "The Hollow Crown",
        "Infinity’s Edge",
        "The Ghosts of Avalon",
        "A Winter’s Promise",
        "The Sapphire Horizon",
        "Song of the Sea",
        "Tales of the Wild",
        "Eternal Nightfall",
        "When Time Stands Still",
        "Legends of the Fallen",
        "The Midnight Run",
        "Secrets of the Enchanted Forest",
        "The Iron Citadel",
        "Chasing the Horizon",
        "The Silent Storm",
        "Across the Silver Plains",
        "Dreams of Tomorrow",
        "The Shadowed Path",
        "Moonlit Echoes",
        "The Phoenix's Cry",
        "Voices in the Dark",
        "The Edge of Forever",
        "Beneath the Broken Stars",
        "The Wandering Soul",
        "Heart of the Abyss",
        "The Burning Chronicles",
        "Frozen in Time",
        "The Celestial Crown",
        "Fate’s Gambit",
        "Beyond the Endless Sky",
        "The Vanishing Light",
        "Whispers of the Past",
        "The Eternal Flame",
        "Chronicles of the Lost Kingdom",
        "The Astral Gate",
        "The Crimson Blade",
        "Echoes of the Deep",
        "The Final Passage",
        "Dawn of the Rising Sun",
        "The Glass Fortress",
        "Shadows of the Forgotten",
        "The Emerald Haven",
        "The Last Chronicle",
        "The Lunar Curse",
        "Fallen Empire",
        "The Twilight Rift",
        "Winds of Change",
        "The Silver Key",
        "The Neon Frontier",
        "Secrets of the Ocean’s Heart",
        "Rise of the Guardians",
        "The Shimmering Path",
        "Legends of the Storm",
        "The Forgotten Quest",
        "Through the Mystic Veil",
        "The Boundless Realm",
        "Embers of the Past",
        "The Infinite Voyage",
        "The Hollow Eclipse",
        "Daughters of the Moon",
        "The Starborn Legacy",
        "Tides of Eternity",
        "The Forgotten Kingdom",
        "The Obsidian Throne",
        "The Eternal Voyage",
        "The Clockwork Realm",
        "Wings of Fire",
        "The Dragon’s Path",
        "Shattered Horizons",
        "The Hidden Codex",
        "Spirits of the Ancients",
        "The Winter King",
        "The Spiral Gate",
        "A Light in the Dark",
        "Echoes Across the Void",
        "The Mystic Prophecy",
        "The Forgotten Realm",
        "Destiny’s Hand",
        "The Night’s Watch",
        "The Endless River",
        "Warden of the Lost",
        "The Riftborn Saga",
        "When Stars Collide",
        "The Amber Citadel",
        "Legends of Dawn",
        "The Veil of Illusion",
        "The Shadow’s Embrace",
        "The Frozen Compass",
        "The Last Skyfarer",
        "The Ethereal Quest",
        "The Starlight Keep",
        "Guardians of the Rift",
        "The Phantom Tides"
    ]   

    movies = []

    for _ in range(num_movies):
        title = random.choice(titles)  # Add variety to titles
        year = random.randint(1980, 2023)
        score = round(random.uniform(1, 10), 1)  # Scores between 1.0 and 10.0
        movies.append((title, year, score))
    
    return movies

# Generate 1000 movies
movies = generate_movies(1000)